### ISSUE TITLE
Can't compile the project

### ISSUE THREAD

**Issue by itapi** [bp2008/x264net#1]
Hello!
I'm very interested in your projects...especially this one... but when i download and rebuild the project... i'm getting tons of errors...

![image](https://cloud.githubusercontent.com/assets/10478457/25637848/08bcb272-2f8f-11e7-8216-06fb49842f0c.png)

i use the lastest Visual studio version(2017)...

Do you have any idea why I'm getting all these errors? 
Thanks!

**Comment by bp2008** [comment]
I will try building with VS 2017 and see what happens.

**Comment by itapi** [comment]
@bp2008  It asks me if i want to update the build tools to v141 to compile this project...I hit yes..
Do you get the same message box?

**Comment by bp2008** [comment]
Yes, I did.

**Comment by bp2008** [comment]
I updated the solution and project files, and it now builds in my VS 2017.  I suggest you redownload and try again.

**Comment by bp2008** [comment]
It can help to hide the IntelliSense errors and show only Build errors in the Error List tab.  But even if you do this, you don't really know which error occurred first (the first error is often the only one that matters).  Best to look at the "Output" tab which shows actual compiler output in the order it occurred.  Find the first error there.

**Comment by itapi** [comment]
@bp2008  Hey!
Thanks for the fast response , i wasn't home in the last 2 days so i couldn't really answer.

![image](https://cloud.githubusercontent.com/assets/10478457/25722462/02186b70-311d-11e7-80b4-7a2fcd177315.png)


Downloaded and rebuild again....these are the errors...

seems like i dont have the right .net version?

**Comment by bp2008** [comment]
It does seem like you do not have the correct .NET version (which is odd, I thought 4.6.2 came with VS 2017).

I'm also surprised your x264net project is showing as a VS 2015 project, since I upgraded it and I certainly do not get that message on mine.

**Comment by itapi** [comment]
@bp2008 Actually i have .net 4.7....
![image](https://cloud.githubusercontent.com/assets/10478457/25737052/4f529814-317e-11e7-9a2e-0d9e10d69ba3.png)


I really appreciate your help :) 
Shall i downgrade to 4.6.2?

**Comment by bp2008** [comment]
I imagine you can have 4.6.2 and 4.7 installed at the same time.  I've not got 4.7 at all yet.

**Comment by itapi** [comment]
@bp2008  got any idea what to do?

**Comment by bp2008** [comment]
What do you have in your Target framework dropdown, in the TestX264Net project properties?

The C++ project (x264net) was automatically configured to build for .net 4.6.1 when I did the upgrade.  Maybe you can change that version to 4.7 or whatever you do have available.  I'm not sure what compatibility issues there may be though.

**Comment by bp2008** [comment]
Someone informed me of a project configuration problem (I had hard-coded one of the paths) so in case you were still having trouble with this, you can get latest and try again.  I also included the required Visual C++ dll files, eliminating the need to install Visual C++ redistributable packages.

**Comment by itapi** [comment]
@bp2008  Thanks! Indeed it works!
How can i watch the h.264 created file? both windows media player & BSplayer don't play it....

**Comment by bp2008** [comment]
VLC media player will play it.

Note it is simply raw H.264 (Annex B I think the format would be called) which can't specify a frame rate.  I think VLC defaults to play these at something like 10 FPS.  x264 does have a frame rate setting but I believe that is only so it can correctly allocate the right slice of your total bit rate to each frame.

If you need to produce a video that will play properly in other players, you can probably feed it into ffmpeg,  specify an output frame rate and mp4 or mkv format.

**Comment by itapi** [comment]
@bp2008  Thank you so much!
Actually I work quite long time on a  small screen sharing project,for learning purposes..I thought  I may use your .net h264 implemention......
Thank you so much!

**Comment by bp2008** [comment]
Neat.  In that case you wouldn't want to use any of the standard video file formats anyway.  I still haven't managed to integrate this code into any of my own projects yet, though eventually I hope to use it in a self-hosted remote desktop program I've been *slowly* working on for about a year.

It is a shame that x264 is only an encoder and not a decoder, because it is only one piece of the puzzle.

**Comment by itapi** [comment]
@bp2008  yeah you right...

I would like to see your remote desktop project too...
I'm in the middle of developing a small ,efficient and fast  codec...on the concept of comparing previous and current frame...sending deltas....I also use the `TurboJpeg` library for performance...also `LZ4` for small data case...

I would really like to see and hear more from you ,specially about this subject.

**Comment by bp2008** [comment]
;)

Alas, my remote desktop project is a **long** way from being usable.  I haven't even put it on github yet.

I've been using the sharpdx library as one of my methods for desktop capture.  Its API is painful to work with but it is great for CPU and network efficiency.  You don't have to do any of your own image analysis. 
 The library basically gives you a list of rectangles that "moved" on the desktop, and another list of rectangles that changed.  If nothing is changing on the desktop, then CPU usage drops to almost nothing as you just sit and wait for the next change to be reported so you can encode the information and send it over the network.

**Comment by itapi** [comment]
@bp2008  Oh yeah...I know the desktop duplication api service and used it few times...Still decided to write a codec for 2 main reasons:
1)This api works  only on Windows 8/10.(In 7 and under I used to call  the `BitBlt` method.
2)The `MovedRegions`  rectangles aren't so accurate  99% of the times it contains extra unnecessary pixels.... Tons of extra data after few frames.

**Comment by bp2008** [comment]
Yeah it isn't the best accuracy, so a good comparison algorithm could be very helpful.

However if doing h.264 encoding, I guess it won't matter whether you know what changed or not since you'll be encoding the complete frame anyway.

**Comment by itapi** [comment]
@bp2008  yep.
So I combine the both "techniques"- I use my own little codec only for the areas which had changed.
