### ISSUE TITLE
Can't compile the project

### ISSUE THREAD

**Issue by pwzh2017** [bp2008/x264net#2]
Hi hello
Because there is no English, the following translation software translation
Operating system: win7
Tools: VS2010
Compile error as shown [below]

![qq 20170527162350](https://cloud.githubusercontent.com/assets/28996547/26519792/f2850324-42f8-11e7-950b-9a09c318ebb1.png)

**Comment by bp2008** [comment]
This project was written for Visual Studio 2017.  The free "Community" edition should work fine.

https://www.visualstudio.com/downloads/

**Comment by bp2008** [comment]
Someone informed me of a project configuration problem (I had hard-coded one of the paths) so in case you were still having trouble with this, you can get latest and try again.  I also included the required Visual C++ dll files, eliminating the need to install Visual C++ redistributable packages.
