### ISSUE TITLE
Doesn't compile out of the box

### ISSUE THREAD

**Issue by eslindsey** [bp2008/x264net#3]
I had to change:
![original settings](http://i.imgur.com/Y4RRkXd.png)
to:
![modified settings](http://i.imgur.com/d88nnkV.png)
to get this project to compile.

Until I made this change, I was receiving a LNK1104 error.

**Comment by bp2008** [comment]
Oops.  Apparently I have an absolute path under Linker > General > Additional Library Directories.

That will be the cause of this.

**Comment by bp2008** [comment]
Thanks for letting me know about this.  I've committed the fix and also included the required Visual C++ dll files, eliminating the need to install Visual C++ redistributable packages.
